### ISSUE TITLE
Add intensity measurements

### ISSUE THREAD

**Issue by tischi** [embl-cba/ome-zarr-image-analysis-nextflow#9]
It would be great to also add intensity measurements to the `MORPHOMETRY` process because this would require us to `.join()` the input image and the segmented image; thereby we would demonstrate another important concept in this example.

**Comment by BioinfoTongLI** [comment]
this is also done in the new repo  :) 
https://github.com/BioImageTools/ome-zarr-image-analysis-nextflow/blob/main/bin/extract_features.py#L35-L39
